console.log("Hey, Welcome to the ACO beta test")
console.log("This data will be used to make the main SMARTi better, so the more you use it the more it helps out!")
console.log("Note none of this data is saved and that this is only going to be used to make the AI speech and text better!")
console.log("There is no need to fill real info, just anything to make the AI work.")
console.log("----------------------")

var dun=prompt("Do you understand this is 100% for testing the new AI and not for storing your data?")
var myname=prompt("Please enter your name")
var myage=prompt("Please enter your age")
var like=prompt("How well do you like this bot?")
var howu=prompt("How are you doing?")
var favcol=prompt("What is your favorite color?")

console.log("Nice to meet you",myname)
console.log("Wow, you are",myage)
console.log("Thanks for the feedback! You said this AI was:",like)
console.log("Hope I can make it better! You said your day was:",howu)
console.log("I like it too, I will make your backround color as close as I can to it! You may also enter a custom color like #f20dfas. Im making it:",favcol)
console.log("Thank you for helping us!")
console.log("Each time you use this, we get to improve our app!")
